version: '3.8'

services:
  advanced-notes-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advanced-notes-app
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge